### ISSUE TITLE
[JavaScript] What the hell is b?

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/open-class#11]
There is a function in the PoorCode.html file named "b". What does that even mean? Rename the function and add some comments describing what it does!

https://github.com/SergeyOvchinnik/open-class/blob/main/web/PoorCode.html#L129

**Comment by JeromeJaggi** [comment]
Working on this

**Comment by SergeyOvchinnik** [comment]
Fixed in:
https://github.com/SergeyOvchinnik/open-class/pull/45
