### ISSUE TITLE
[JavaScript] Code quality in casing

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/open-class#13]
function casing in PoorCode.html file has some code quality issues, please fix.

https://github.com/SergeyOvchinnik/open-class/blob/main/web/PoorCode.html#L173

**Comment by 2441630833** [comment]
This issue will be fixed by me

**Comment by SergeyOvchinnik** [comment]
Fixed in:
https://github.com/SergeyOvchinnik/open-class/pull/44
